/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Others;

import Destination.destination_main;
import Oil.oil_main;
import Others.functions;
import Reports.volume_summary;
import Vale.vale_main;
import Vehicle.vehicle_main;
import Others.image_attribution;
import Reports.FuelAccountsPayable;
import Reports.TopVolume;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class main_menu extends javax.swing.JFrame {

    public static volume_summary rptvolume_summary;
    public static TopVolume rptTopvolume;
    public static FuelAccountsPayable rptFuelAccountsPayable;

    /**
     * Creates new form vale_menu
     */
    public main_menu() {
        initComponents();
        this.setLocationRelativeTo(null);  //to center JFrame
        try {
            imageCredits();
        } catch (IOException ex) {
            Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuModules = new javax.swing.JMenu();
        mnu_itemVale = new javax.swing.JMenuItem();
        mnu_itemDestination = new javax.swing.JMenuItem();
        mnu_itemFuel = new javax.swing.JMenuItem();
        mnu_itemVehicle = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnu_itemVolume = new javax.swing.JMenuItem();
        mnu_TopVolume = new javax.swing.JMenuItem();
        mnu_AccountsPayable = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setWheelScrollingEnabled(false);

        desktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1696, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane))
        );

        jScrollPane1.setViewportView(jPanel2);

        mnuBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuBarKeyPressed(evt);
            }
        });

        mnuModules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/module_64.png"))); // NOI18N
        mnuModules.setMnemonic('M');
        mnuModules.setText("Modules");

        mnu_itemVale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket_24.png"))); // NOI18N
        mnu_itemVale.setMnemonic('V');
        mnu_itemVale.setText("Vale");
        mnu_itemVale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_itemValeActionPerformed(evt);
            }
        });
        mnuModules.add(mnu_itemVale);

        mnu_itemDestination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/destination_24.png"))); // NOI18N
        mnu_itemDestination.setMnemonic('D');
        mnu_itemDestination.setText("Destination");
        mnu_itemDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_itemDestinationActionPerformed(evt);
            }
        });
        mnuModules.add(mnu_itemDestination);

        mnu_itemFuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fuel_24.png"))); // NOI18N
        mnu_itemFuel.setMnemonic('F');
        mnu_itemFuel.setText("Oil");
        mnu_itemFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_itemFuelActionPerformed(evt);
            }
        });
        mnuModules.add(mnu_itemFuel);

        mnu_itemVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_24.png"))); // NOI18N
        mnu_itemVehicle.setMnemonic('e');
        mnu_itemVehicle.setText("Vehicle");
        mnu_itemVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_itemVehicleActionPerformed(evt);
            }
        });
        mnuModules.add(mnu_itemVehicle);

        mnuBar.add(mnuModules);

        mnuReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report_64.png"))); // NOI18N
        mnuReports.setMnemonic('R');
        mnuReports.setText("Reports");

        mnu_itemVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volume_24.png"))); // NOI18N
        mnu_itemVolume.setMnemonic('o');
        mnu_itemVolume.setText("by Volume");
        mnu_itemVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_itemVolumeActionPerformed(evt);
            }
        });
        mnuReports.add(mnu_itemVolume);

        mnu_TopVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volume_24.png"))); // NOI18N
        mnu_TopVolume.setText("Top Volume by Vehicle");
        mnu_TopVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_TopVolumeActionPerformed(evt);
            }
        });
        mnuReports.add(mnu_TopVolume);

        mnu_AccountsPayable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volume_24.png"))); // NOI18N
        mnu_AccountsPayable.setText("Fuel/Oil Accounts Payable");
        mnu_AccountsPayable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_AccountsPayableActionPerformed(evt);
            }
        });
        mnuReports.add(mnu_AccountsPayable);

        mnuBar.add(mnuReports);

        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_64.png"))); // NOI18N
        mnuExit.setMnemonic('x');
        mnuExit.setText("Exit");
        mnuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExitMouseClicked(evt);
            }
        });
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuExitKeyPressed(evt);
            }
        });
        mnuBar.add(mnuExit);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isFormAdded(JDesktopPane desktopPane, Component formContent) {
        for (Component component : desktopPane.getComponents()) {
            if (component instanceof JInternalFrame) {
                JInternalFrame internalFrame = (JInternalFrame) component;
                if (internalFrame.getContentPane().equals(formContent)) {
                    return true;
                }
            }
        }
        return false;
    }

    private void mnuBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuBarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBarKeyPressed

    private void mnuExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuExitKeyPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuExitKeyPressed

    private void mnu_itemVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_itemVolumeActionPerformed
        // TODO add your handling code here:
//        JDialog dialog = new JDialog(this, "By Volume", true);
//        volume_main form = new volume_main();
//        dialog.getContentPane().add(form.getContentPane());
//        dialog.pack();
//        dialog.setLocationRelativeTo(this);
//        dialog.setVisible(true);

//        volume_summary form = new volume_summary(); 
//        desktopPane.add(form);
//        form.setVisible(true);
//        JInternalFrame volumeSummaryFrame = new JInternalFrame("Volume Summary", true, true, true, true);
//        volumeSummaryFrame.setContentPane(form.getContentPane());
//        volumeSummaryFrame.setSize(form.getSize());
//        volumeSummaryFrame.setVisible(true);
//
//        desktopPane.add(volumeSummaryFrame);
        rptvolume_summary = new volume_summary(this, true);      //CAll sales form
        rptvolume_summary.setVisible(true);
    }//GEN-LAST:event_mnu_itemVolumeActionPerformed

    private void mnu_itemValeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_itemValeActionPerformed
        // TODO add your handling code here:
        vale_main form = new vale_main();

        if (!isFormAdded(desktopPane, form.getContentPane())) {
            JInternalFrame internalFrame = new JInternalFrame("Vale Transactions", true, true, true, true);
            internalFrame.setContentPane(form.getContentPane());
            internalFrame.setSize(form.getSize());
            internalFrame.setVisible(true);

            try {
                internalFrame.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
            }

            desktopPane.add(internalFrame);
        }
    }//GEN-LAST:event_mnu_itemValeActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuExitMouseClicked

    private void mnu_itemDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_itemDestinationActionPerformed
        // TODO add your handling code here:
        destination_main form = new destination_main();

        if (!isFormAdded(desktopPane, form.getContentPane())) {
            JInternalFrame internalFrame = new JInternalFrame("Destinations", true, true, true, true);
            internalFrame.setContentPane(form.getContentPane());
            internalFrame.setSize(form.getSize());
            internalFrame.setVisible(true);

            desktopPane.add(internalFrame);
        }
    }//GEN-LAST:event_mnu_itemDestinationActionPerformed

    private void mnu_itemFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_itemFuelActionPerformed
        // TODO add your handling code here:
        oil_main form = new oil_main();

        if (!isFormAdded(desktopPane, form.getContentPane())) {
            JInternalFrame internalFrame = new JInternalFrame("Oil Entries", true, true, true, true);
            internalFrame.setContentPane(form.getContentPane());
            internalFrame.setSize(form.getSize());
            internalFrame.setVisible(true);

            desktopPane.add(internalFrame);
        }
    }//GEN-LAST:event_mnu_itemFuelActionPerformed

    private void mnu_itemVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_itemVehicleActionPerformed
        // TODO add your handling code here:
        vehicle_main form = new vehicle_main();

        if (!isFormAdded(desktopPane, form.getContentPane())) {
            JInternalFrame internalFrame = new JInternalFrame("Vehicle Entries", true, true, true, true);
            internalFrame.setContentPane(form.getContentPane());
            internalFrame.setSize(form.getSize());
            internalFrame.setVisible(true);

            desktopPane.add(internalFrame);
        }
    }//GEN-LAST:event_mnu_itemVehicleActionPerformed

    private void mnu_TopVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_TopVolumeActionPerformed
        rptTopvolume = new TopVolume(this, true);      //CAll sales form
        rptTopvolume.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_mnu_TopVolumeActionPerformed

    private void mnu_AccountsPayableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_AccountsPayableActionPerformed
        rptFuelAccountsPayable = new FuelAccountsPayable(this, true);      //CAll sales form
        rptFuelAccountsPayable.setVisible(true);          // TODO add your handling code here:

    }//GEN-LAST:event_mnu_AccountsPayableActionPerformed

    public void imageCredits() throws FileNotFoundException, IOException {
        image_attribution image1 = new image_attribution("module_64", "https://www.freepik.com/icon/cells_505079#position=2&term=module&fromView=search", new FileInputStream("module_64.png"));
        image1.attributes.put("author", "Freepik");

        image_attribution image2 = new image_attribution("logout_64", "https://www.freepik.com/icon/logout_4400828#position=41&page=1&term=exit&fromView=search", new FileInputStream("logout_64.png"));
        image2.attributes.put("author", "SumberRejeki");

        image_attribution image3 = new image_attribution("report_64", "https://www.freepik.com/icon/analytics_1804059#position=8&term=report&fromView=search", new FileInputStream("report_64.png"));
        image3.attributes.put("author", "DinosoftLabs");

        image_attribution image4 = new image_attribution("ticket_24", "https://www.flaticon.com/free-icons/ticket", new FileInputStream("ticket_24.png"));
        image4.attributes.put("author", "Icongeek26");

        image_attribution image5 = new image_attribution("destination_24", "https://www.flaticon.com/free-icons/pin", new FileInputStream("destination_24.png"));
        image5.attributes.put("author", "Smashicons");

        image_attribution image6 = new image_attribution("fuel_24", "https://www.flaticon.com/free-icons/fuel", new FileInputStream("fuel_24.png"));
        image6.attributes.put("author", "Freepik");

        image_attribution image7 = new image_attribution("car_24", "https://www.flaticon.com/free-icons/car", new FileInputStream("car_24.png"));
        image7.attributes.put("author", "Anatoly");

        image_attribution image8 = new image_attribution("volume_24", "https://www.flaticon.com/free-icons/volumetric-flask", new FileInputStream("volume_24.png"));
        image8.attributes.put("author", "Freepik");

        System.out.println(image1.getAttribution());
        System.out.println(image2.getAttribution());
        System.out.println(image3.getAttribution());
        System.out.println(image4.getAttribution());
        System.out.println(image5.getAttribution());
        System.out.println(image6.getAttribution());
        System.out.println(image7.getAttribution());
        System.out.println(image8.getAttribution());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new main_menu().setVisible(true);
                // Maximize the JFrame

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuModules;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenuItem mnu_AccountsPayable;
    private javax.swing.JMenuItem mnu_TopVolume;
    private javax.swing.JMenuItem mnu_itemDestination;
    private javax.swing.JMenuItem mnu_itemFuel;
    private javax.swing.JMenuItem mnu_itemVale;
    private javax.swing.JMenuItem mnu_itemVehicle;
    private javax.swing.JMenuItem mnu_itemVolume;
    // End of variables declaration//GEN-END:variables
}
